# Introduction to Deep Learning with PyTorch

# Tensors

It turns out neural network computations are just a bunch of linear algebra operations on tensors, a generalization of matrices. A vector is a 1-dimensional tensor, a matrix is a 2-dimensional tensor, an array with three indices is a 3-dimensional tensor (RGB color images for example). The fundamental data structure for neural networks are tensors and PyTorch (as well as pretty much every other deep learning framework) is built around tensors.



In [1]:
conda install pytorch

Solving environment: done

## Package Plan ##

  environment location: /home/imran/anaconda3

  added / updated specs:
    - pytorch


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    _pytorch_select-0.2        |            gpu_0           2 KB
    cudatoolkit-10.0.130       |                0       261.2 MB
    cudnn-7.6.5                |       cuda10.0_0       165.0 MB
    ninja-1.9.0                |   py37hfd86e86_0         1.2 MB
    pytorch-1.3.1              |cuda100py37h53c1284_0       169.0 MB
    ------------------------------------------------------------
                                           Total:       596.4 MB

The following NEW packages will be INSTALLED:

  _pytorch_select    pkgs/main/linux-64::_pytorch_select-0.2-gpu_0
  cudatoolkit        pkgs/main/linux-64::cudatoolkit-10.0.130-0
  cudnn              pkgs/main/linux-64::cudnn-7.6.5-cuda10.0_0
  ninja            

In [2]:
%matplotlib inline
%config InlineBackend.figure_format = 'retina'

import numpy as np
import torch

import helper

First, let's see how we work with PyTorch tensors. These are the fundamental data structures of neural networks and PyTorch, so it's imporatant to understand how these work.



In [9]:
x = torch.rand(3, 2)
print(x,'\n\n', type(x))

tensor([[0.8212, 0.3404],
        [0.3665, 0.2270],
        [0.2131, 0.1082]]) 

 <class 'torch.Tensor'>


In [10]:
y = torch.ones(x.size())
print(y,'\n\n', type(y))

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]]) 

 <class 'torch.Tensor'>


In [11]:
z = x + y
z

tensor([[1.8212, 1.3404],
        [1.3665, 1.2270],
        [1.2131, 1.1082]])

### In general PyTorch tensors behave similar to Numpy arrays. They are zero indexed and support slicing.



In [12]:
z[0]

tensor([1.8212, 1.3404])

In [13]:
z[:, 1:]

tensor([[1.3404],
        [1.2270],
        [1.1082]])

Tensors typically have two forms of methods, one method that returns another tensor and another method that performs the operation in place. That is, the values in memory for that tensor are changed without creating a new tensor. In-place functions are always followed by an underscore, for example z.add() and z.add_().



In [14]:
# Return a new tensor z + 1
z.add(1)


tensor([[2.8212, 2.3404],
        [2.3665, 2.2270],
        [2.2131, 2.1082]])

In [15]:
# z tensor is unchanged
z

tensor([[1.8212, 1.3404],
        [1.3665, 1.2270],
        [1.2131, 1.1082]])

In [16]:
# Add 1 and update z tensor in-place
z.add_(1)

tensor([[2.8212, 2.3404],
        [2.3665, 2.2270],
        [2.2131, 2.1082]])

In [17]:
# z has been updated
z

tensor([[2.8212, 2.3404],
        [2.3665, 2.2270],
        [2.2131, 2.1082]])

## Reshaping


Reshaping tensors is a really common operation. First to get the size and shape of a tensor use .size(). Then, to reshape a tensor, use .resize_(). Notice the underscore, reshaping is an in-place operation.



In [18]:
z.size()

torch.Size([3, 2])

In [19]:
z.resize_(2, 3)

tensor([[2.8212, 2.3404, 2.3665],
        [2.2270, 2.2131, 2.1082]])

In [20]:
z

tensor([[2.8212, 2.3404, 2.3665],
        [2.2270, 2.2131, 2.1082]])

## Numpy to Torch and back
Converting between Numpy arrays and Torch tensors is super simple and useful. To create a tensor from a Numpy array, use torch.from_numpy(). To convert a tensor to a Numpy array, use the .numpy() method.



In [21]:
a = np.random.rand(4,3)
a

array([[0.37516734, 0.32500046, 0.38358225],
       [0.95560524, 0.98256934, 0.98454549],
       [0.36179341, 0.97087973, 0.47260361],
       [0.15137445, 0.238061  , 0.87275989]])

In [22]:
b = torch.from_numpy(a)
b

tensor([[0.3752, 0.3250, 0.3836],
        [0.9556, 0.9826, 0.9845],
        [0.3618, 0.9709, 0.4726],
        [0.1514, 0.2381, 0.8728]], dtype=torch.float64)

In [23]:
b.numpy()

array([[0.37516734, 0.32500046, 0.38358225],
       [0.95560524, 0.98256934, 0.98454549],
       [0.36179341, 0.97087973, 0.47260361],
       [0.15137445, 0.238061  , 0.87275989]])

The memory is shared between the Numpy array and Torch tensor, so if you change the values in-place of one object, the other will change as well.


In [24]:
# Multiply PyTorch Tensor by 2, in place
b.mul_(2)

tensor([[0.7503, 0.6500, 0.7672],
        [1.9112, 1.9651, 1.9691],
        [0.7236, 1.9418, 0.9452],
        [0.3027, 0.4761, 1.7455]], dtype=torch.float64)

In [25]:
# Numpy array matches new values from Tensor
a

array([[0.75033469, 0.65000091, 0.76716451],
       [1.91121047, 1.96513869, 1.96909098],
       [0.72358682, 1.94175946, 0.94520723],
       [0.30274889, 0.47612199, 1.74551977]])